### ISSUE TITLE
Add a flag to disable user/group creation

### ISSUE THREAD

**Issue by EdwardSkoviak** [cerner/cerner_tomcat#15]
In use cases where a node may be enrolled in a corporate AD, it may not be desirable for the cookbook to create a local user/group. A flag to disable the creation would handle this scenario.

**Comment by EdwardSkoviak** [comment]
Completed by https://github.com/cerner/cerner_tomcat/pull/29

**Comment by cchesser** [comment]
It appears this change by #29, broke the assumption in the tests that a home directory will exist for the user, which is not be created by the LWRP. If you do any of the stop/start/restart commands on the service, it will report the following:

```
Starting my_tomcat:
su: warning: cannot change directory to /home/my_user: No such file or directory
```

I assume the change in #29 wanted set the user to one which it is managing (ex. bound to an AD controller), so that it can actually switch to that user. As a result, an entry does exist in `/etc/passwd` for the user specified in the init.d service file, though, it does not have a home directory. This could be accomplished by just having the integration tests create their own user, and not allow cerner_tomcat do the management of it.

**Comment by EdwardSkoviak** [comment]
The user and group should still be created as part of the my_tomcat installation[1], and we only are setting the new attribute in the subsequent installation of my_tomcat_2 (corresponding skips due to only_if here[2]).

[1] https://gist.github.com/EdwardSkoviak/c83a7d168bdb77cfa05369d4a60d5dba#file-gistfile1-txt-L276-L279
[2] https://gist.github.com/EdwardSkoviak/c83a7d168bdb77cfa05369d4a60d5dba#file-gistfile1-txt-L670-L671

**Comment by cchesser** [comment]
Correct, the user does exist, but the session settings expect to be able to switch to the home directory when the init.d script switches to the user (which the directory does not exist). So there is a passivity issue in how the user was being managed previously by the cerner_tomcat provider, and what was in-place when we set the attribute to `false` in the kitchen tests.

```
su -l $USER -c 
```

This is being used, and by using the `-l` option, we are indicating to "login", which will use the login shell, which will default to switch to their home directory.

**Comment by EdwardSkoviak** [comment]
Ah I see, I'm probably missing something here, but why wasn't this an issue previously?

**Comment by EdwardSkoviak** [comment]
I tested this out on a branch before this change was merged and it looks like we are still seeing this issue.

**Comment by EdwardSkoviak** [comment]
Also tested this out on the v2.2.0 tag:

```
$ sudo /etc/init.d/tomcat_my_tomcat_2 restart
Shutting down my_tomcat_2:
Attempting to shutdown my_tomcat_2...
su: warning: cannot change directory to /home/my_user: No such file or directory
Using CATALINA_BASE:   /opt/my_dir/my_tomcat_2
Using CATALINA_HOME:   /opt/my_dir/my_tomcat_2
Using CATALINA_TMPDIR: /opt/my_dir/my_tomcat_2/temp
Using JRE_HOME:        /usr/lib/jvm/java-1.8.0
Using CLASSPATH:       /opt/my_dir/my_tomcat_2/bin/bootstrap.jar:/opt/my_dir/my_tomcat_2/bin/tomcat-juli.jar
my_tomcat_2 has stopped
Starting my_tomcat_2:
su: warning: cannot change directory to /home/my_user: No such file or directory
Using CATALINA_BASE:   /opt/my_dir/my_tomcat_2
Using CATALINA_HOME:   /opt/my_dir/my_tomcat_2
Using CATALINA_TMPDIR: /opt/my_dir/my_tomcat_2/temp
Using JRE_HOME:        /usr/lib/jvm/java-1.8.0
Using CLASSPATH:       /opt/my_dir/my_tomcat_2/bin/bootstrap.jar:/opt/my_dir/my_tomcat_2/bin/tomcat-juli.jar
Tomcat started.
Waiting for application at http://localhost:8011/my_webapp/hello to start
Health check failed with status 000
Sleeping for 0
Health check failed with status 000
Sleeping for 5
Health check passed with status 200
```

```
$ ls /home/
vagrant
```
