### ISSUE TITLE
Reduce the number of service start-up events on a single chef-client execution

### ISSUE THREAD

**Issue by cchesser** [cerner/cerner_tomcat#16]
For fresh installations of Tomcat (or upgrading Tomcat), typically you will always start the process and then later trigger a delayed restart from a notification. Since all the files which are managed by the LWRP will trigger a delayed restart, would it be acceptable to simply change:

``` ruby
service "tomcat_#{new_resource.instance_name}" do
  supports status: true, restart: true
  action [:enable, :start]
end
```

to:

``` ruby
service "tomcat_#{new_resource.instance_name}" do
  supports status: true, restart: true
  action [:enable]
end
```

This will avoid the starting of the service, and await the delayed restart that will inherently occur from any other file managed in the LWRP. As a result, you will on get a single start of that process at the end, which can reduce the total `chef-client` run.

**Comment by bbaugher** [comment]
Yes I think that would be beneficial. I would think we should still have the start action though as thats the state we want it in. Although it seems unlikely if it dies but everything is installed and configured chef should start it back up.

The simplest implementation would be to make the actions configurable. Another option could be to have some smarts around handling either sending the restart notifications or starting the service.

**Comment by cchesser** [comment]
Thanks @bbaugher.

> The simplest implementation would be to make the actions configurable.

OK, would you prefer that we only just make it configurable for adding `:start`, as it would seem if we added other actions, the overall LWRP wouldn't really workout on what it is ultimately setting up. Also, I wouldn't want someone to essentially not include `:enable`. 

I originally looked at this option that was applied with [cerner_splunk](https://github.com/cerner/cerner_splunk) [1,2], but there is a decent amount of complexity for something that seems to be really just be flexed for the event of initially starting, and then later restarting.

[1] http://stackoverflow.com/questions/21066591/minimize-service-restarts-from-chef-notifications
[2] https://github.com/cerner/cerner_splunk/commit/c79d4553522ff69e36af4e4a5a30194db803f424

**Comment by bbaugher** [comment]
I don't think I have a particular preference. 

Seems like it might not be too difficult to handle the installation case where if the installation doesn't exist we don't try to start it.

**Comment by cchesser** [comment]
Sounds good, I will follow-up with a PR where we can complete the discussion on the implementation choice.

**Comment by bbaugher** [comment]
Completed by #19
