### ISSUE TITLE
ulimit settings are hard-coded in the provider

### ISSUE THREAD

**Issue by cchesser** [cerner/cerner_tomcat#17]
Currently, max process and open file limits are [hard-coded by the LWRP](https://github.com/cerner/cerner_tomcat/blob/v2.1.1/providers/default.rb#L31-L33):

``` ruby
  # Setup ulimits
  node.default['ulimit']['users'][new_resource.user]['filehandle_limit'] = 32_768
  node.default['ulimit']['users'][new_resource.user]['process_limit'] = 1024

  run_context.include_recipe 'ulimit'
```

It would be ideal to utilize the `user_ulimit` resource by the [ulimits cookbook](https://github.com/bmhatfield/chef-ulimit), and take in a hash for a `ulimit` attribute, that can allow customization of these values.

**Comment by bbaugher** [comment]
Fixed by #18
