### ISSUE TITLE
find_pid within init.d script can qualify different Tomcat installations 

### ISSUE THREAD

**Issue by cchesser** [cerner/cerner_tomcat#21]
When a consumer installs multiple instances of Tomcat on a host, it cause a scenario where the `find_pid` bash function, can actually qualify a wrong instance (based on the naming applied by the consumer). Example:
- my_app
- my_app_1

With these two, there could be the following installations (and running PIDs):
- /opt/tomcat/my_app (pid: 123)
- /opt/tomcat/my_app_2 (pid: 456)

While both of these service processes are running, you could issue `service tomcat_my_app status`, but it actually qualifies PID 456 (rather than PID 123). This because the `find_pid` function is not terminating on the `$CATALINA_HOME` with a slash, and follows it with a `.*`.

``` bash
find_pid() {
  PID=`pgrep -u $USER -f "$CATALINA_HOME.*$START_CLASS"`
}
```

Where `$CATALINA_HOME` can be `/opt/tomcat/my_app` in the script, which allows it to qualify `/opt/tomcat/my_app_1` when executing pgrep. One proposed way of fixing this, is terminating the `$CATALINA_HOME` with `/`.

**Comment by bbaugher** [comment]
Thats unfortunate. The solution seems like a good idea. 

Further down the road we may want to consider moving off init to either upstart or systemd. I know for upstart you can just specify the command to run the service and it handles the rest.

**Comment by cchesser** [comment]
Agreed. Do we want to have a different issue logged for the tech uplift on these?

**Comment by bbaugher** [comment]
Logged #22 for that uplift
