### ISSUE TITLE
Upgrade off init to upstart/systemd/etc

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_tomcat#22]
Mentioned in #21 our ancient init script isn't fun to take care of and some of the newer system services can make this much easier. We should look to move to something like upstart or systemd

**Comment by EdwardSkoviak** [comment]
Probably worth looking into using poise-service[1]. I haven't dug much into how it works, but looks like we could support dependency injection of the service management framework the cookbook user wants.

[1] https://github.com/poise/poise-service

**Comment by EdwardSkoviak** [comment]
I spoke with Noah Kantrowitz (author of the Poise family of cookbooks) yesterday and he said making this switch would be very simple, linked to the following:

[poise-service resource call](https://github.com/coderanger/octan_demo/blob/master/cookbooks/octan_backend/recipes/default.rb#L82-L88)
[single line command we'd need](https://github.com/coderanger/octan_demo/blob/master/cookbooks/octan_backend/templates/run.sh.erb#L52)

The rest would basically be handled by the provider in poise-service.

As for a replacements for our health check functionality, we could do something similar to this:

https://github.com/poise/jenkins/blob/master/libraries/jenkins.rb#L185-L197

**Comment by EdwardSkoviak** [comment]
Added support with #35
