### ISSUE TITLE
Support additional command line options for health checks

### ISSUE THREAD

**Issue by EdwardSkoviak** [cerner/cerner_tomcat#23]
Add support for adding additional command line options for cURL when performing health checks.

**Comment by EdwardSkoviak** [comment]
This issue was opened primarily so insecure health checks could be made. Probably better to avoid leaking implementation details by allowing command line options for cURL to be passed, and instead just add support for insecure health checks instead. Thoughts?

**Comment by EdwardSkoviak** [comment]
Two potential implementations:

[insecure health checks](https://github.com/cerner/cerner_tomcat/commit/add61e09d21e4a35e3ffa409dd5d654437cc4429)

[allow additional command line options](https://github.com/cerner/cerner_tomcat/commit/8787b78ae25f2516eeee6d894a2fb97f3a9ed924)

**Comment by bbaugher** [comment]
I prefer the additional command line options as that seems more flexible. Do you think we would ever need to override/remove existing options? I'm fine with keeping it simple, just curious mostly

**Comment by EdwardSkoviak** [comment]
Good question, here is the current curl command we are executing:

> curl "--$2" -s -L -w "%{http_code}\n" "$1" --max-time "$3" -o /dev/null ${@:4}

-s, -w [arg], and -o [arg] are necessary so we can get ONLY the desired output returned to our methods calling to the health check method. max-time is already configurable, and well as the HTTP command. -L is used to follow redirects, which we could be the most flexible on removing, but probably not very likely.

**Comment by noslowerdna** [comment]
I like the additional args.

**Comment by mkwhitacre** [comment]
+1 additional args

**Comment by EdwardSkoviak** [comment]
putting out a pull for additional args[1].

[1] https://github.com/cerner/cerner_tomcat/pull/30

**Comment by EdwardSkoviak** [comment]
Merged https://github.com/cerner/cerner_tomcat/pull/30 in.
