### ISSUE TITLE
Verbose failure logs on cerner_tomcat provider failure

### ISSUE THREAD

**Issue by cchesser** [cerner/cerner_tomcat#24]
We are getting large amount of contents in our chef-client logs, which are causing downstream failures in our chef-client runs. The typical downstream point of failure is the Chef reporter, which attempts to post all the resource updates (and failures), which eventually times out after minutes of trying to send the contents.

Here is an [example log](https://gist.githubusercontent.com/cchesser/ec083cda125054073ec0dcb55a36a558/raw/455e150fe53eab66832d6b46129364a634f10db0/chef-client.log) (note, you need to view it through the raw view to see the full contents of the gist), when I changed the integration tests for this project to hit an invalid end-point for the health check.

This hash of attributes looks to be a result of our custom class definitions which extend our `Block` class  (ex. `class HealthCheckBlock < Block`), which have this massive expansion of definition.

**Comment by bbaugher** [comment]
haha, yes I think I've seen that before. I'll see what I can do to make that better

**Comment by cchesser** [comment]
Yeah, we have a decent amount of application converged on a single host, which makes this hash _HUGE_ (puts your terminal logging to the test).

Is there an implied `to_text` / `to_json` which is getting invoked at the point of logging from chef-client that needs to be handled (to avoid this default behavior)? I can help on this change if you can share your design thoughts.

**Comment by bbaugher** [comment]
I have no idea. My current thought is its just doing `object.inspect` which I believe prints all the variables of the class, but I really don't know how to fix it

**Comment by cchesser** [comment]
I assume the direct log is tied to the `to_text` call on the resource, via the [ResourceFailureInspector](https://github.com/chef/chef/blob/v12.16.5/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb#L46).

**Comment by EdwardSkoviak** [comment]
Just wanted to bring up that this also prints sensitive information that is stored in the object during runtime (database passwords/o-auth secrets/etc).

**Comment by EdwardSkoviak** [comment]
A simple fix for this is to set the sensitive flag on the cerner_tomcat resource. The output then looks something like this:

```
           Resource Declaration:
           ---------------------
           suppressed sensitive resource output

           Compiled Resource:
           ------------------
           suppressed sensitive resource output

           Platform:
           ---------
           x86_64-linux
```

**Comment by EdwardSkoviak** [comment]
Made the resource sensitive by default with this pull #34

**Comment by cchesser** [comment]
I'm good with closing this issue out (since #34 resolved the primary issue). Being that you may want this logged out when troubleshooting, and wanting the content limited (vs. the massive blob), it may make sense to leave open, but I would be comfortable with closing it (being the one who originally logged it).
