### ISSUE TITLE
Does not support all actions specified in the documentation

### ISSUE THREAD

**Issue by taharah** [cerner/cerner_tomcat#36]
The README lists that the actions ":start, :stop, :restart, :reload" are available for the cerner_tomcat resource; however, it looks like only :enable, :disable, and :nothing are actually supported. The resource is unable to take in the aforementioned actions, which would be great for setting the resource to restart after installing or something similar.

**Comment by EdwardSkoviak** [comment]
Those actions are actually provided by the poise-service ServiceMixin[1]. As you can see here[2], we are calling the restart action on the resource.

[1] https://github.com/cerner/cerner_tomcat/blob/master/libraries/cerner_tomcat.rb#L133
[2] https://github.com/cerner/cerner_tomcat/blob/master/libraries/cerner_tomcat.rb#L197

**Comment by EdwardSkoviak** [comment]
If you are still running into an issue calling the other actions, please provide some example code so I can help you locate the problem.

**Comment by addy** [comment]
I'm also experiencing an error with the :create action in web_app.rb

`[0mNoMethodError[0m
-------------[0m
undefined method `action' for CernerTomcat::Resources::WebApp::Resource:Class[0m

[0mCookbook Trace:[0m
---------------[0m
  /var/chef/cache/cookbooks/cerner_tomcat/libraries/web_app.rb:58:in `<class:Resource>'
[0m  /var/chef/cache/cookbooks/cerner_tomcat/libraries/web_app.rb:23:in `<module:WebApp>'
[0m  /var/chef/cache/cookbooks/cerner_tomcat/libraries/web_app.rb:22:in `<module:Resources>'
[0m  /var/chef/cache/cookbooks/cerner_tomcat/libraries/web_app.rb:21:in `<module:CernerTomcat>'
[0m  /var/chef/cache/cookbooks/cerner_tomcat/libraries/web_app.rb:20:in `<top (required)>'[0m`

**Comment by EdwardSkoviak** [comment]
There aren't actions defined for the web_app psuedo-subresource.

**Comment by EdwardSkoviak** [comment]
Reached out to @x4nt through Corporate channels and discussed his problem, looked to be a problem with using an unsupported Chef version. Updating to Chef 12+ looked to have resolved his issue.

**Comment by EdwardSkoviak** [comment]
Spoke with @taharah as well and turns out he was using 2.3.0 which doesn't support the new actions.
