### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by EdwardSkoviak** [cerner/cerner_tomcat#38]
[Issues](https://github.com/cerner/cerner_tomcat/issues?q=is%3Aissue+milestone%3A3.0.0+is%3Aclosed)
[Test evidence](https://gist.github.com/EdwardSkoviak/1a08f836f2c03818c4e2ab20f6dac4a8)

**Comment by bbaugher** [comment]
+1

**Comment by mkwhitacre** [comment]
+1

**Comment by EdwardSkoviak** [comment]
Released,

https://github.com/cerner/cerner_tomcat/tree/v3.0.0
https://supermarket.chef.io/cookbooks/cerner_tomcat/versions/3.0.0
