### ISSUE TITLE
Remove size as default logrotate option

### ISSUE THREAD

**Issue by ddellspe** [cerner/cerner_tomcat#40]
With logrotate when you specify size, the log then rotates by [size rather than frequency]. Because of this, there's now way to get a weekly logrotate using cerner_tomcat currently.  If size were removed, those who leverage the cookbook could do a frequency-based rotate (or size-based if specified).

[size rather than frequency]: https://github.com/logrotate/logrotate/blob/master/config.c#L1051

**Comment by bbaugher** [comment]
I believe this may be fixed in the 3.0.0 version of the cookbook where the [defaults](https://github.com/cerner/cerner_tomcat/blob/v3.0.0/libraries/cerner_tomcat.rb#L52) are provided as the default value and not [merged](https://github.com/cerner/cerner_tomcat/blob/v2.3.0/providers/default.rb#L106) with what is provided.

**Comment by ddellspe** [comment]
Both the README and my experience say it still gets merged.  I think it's because it's a lazy default that it merges them in, perhaps.  I haven't been able to pinpoint what's actually going on with why I'm still getting the size attribute when I don't specify it in my parameters.

**Comment by EdwardSkoviak** [comment]
The merging of the default values with what is passed in is a feature of the poise option_collector[1], lazy evaluation just delays when the value is resolved.

[1] https://github.com/poise/poise#option-collector

**Comment by ddellspe** [comment]
So, this would tell me that the options are merging, correct?  If that is the case retaining size as an option would make it not possible to have a frequency-based logrotate file.
