### ISSUE TITLE
Support checksum for web_app primary source

### ISSUE THREAD

**Issue by mattnelson** [cerner/cerner_tomcat#50]
The chef [remote_file resource](https://docs.chef.io/resource_remote_file.html#properties) supports the ability to supply a checksum to prevent additional downloads when the file hasn't changed. Given a large enough resource or slow network connection this can cause a considerable bottle neck. Would it be possible to accept an optional checksum attribute in [web_app](https://github.com/cerner/cerner_tomcat/blob/v3.1.0/libraries/web_app.rb#L64-L74) then supply that the remote_file?

**Comment by bbaugher** [comment]
Yes that would be pretty simple. There also the [conditional get](https://docs.chef.io/resource_remote_file.html#prevent-re-downloads) method as well which is already provided

**Comment by mattnelson** [comment]
Marking this as closed since it has been merged into [master](#52 ) and [2.x](#53 )

**Comment by cchesser** [comment]
I noticed this was merged back to the 2.x line, but there hasn't been a release yet of 2.5.0. Is there a release planned for this? Thanks!

**Comment by bbaugher** [comment]
This was released, https://supermarket.chef.io/cookbooks/cerner_tomcat/versions/2.5.0

**Comment by cchesser** [comment]
Thanks @bbaugher!
