### ISSUE TITLE
Compatibility with java 2.x

### ISSUE THREAD

**Issue by nibroc** [cerner/cerner_tomcat#55]
The Java cookbook has now released a 2.x line. Since other cookbooks are starting to require it, cerner_tomcat is becoming incompatible with things. Would there be any objections to a pull request that gets cerner_tomcat onto java 2.x? Alternatively, how about a pull request that makes it so that the java cookbook is simply not included through cerner_tomcat and consumers can add it to their run_list if they want?

**Comment by bbaugher** [comment]
I think I'd be fine with either option

**Comment by nibroc** [comment]
Closing since someone else did it in #57
